source 'https://github.com/CocoaPods/Specs.git'
source 'git@coding.jiamiantech.com:ce/LRSDevRepo/LRSRepos.git'

use_frameworks!

platform :ios, '11.0'

target 'AFNetworking-RACExtensions-JM_Example' do
  pod 'LRSRACAFNetworking', :path => '../'
end
