use_frameworks!

platform :ios, '8.0'

target 'AFNetworking-RACExtensions-JM_Example' do
  pod 'AFNetworking-RACExtensions-JM', :path => '../'

  target 'AFNetworking-RACExtensions-JM_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
